# -*- coding: utf-8 -*-
{
    'name': "School_Management",
    'version': "19.0.1.0.0",
    'license':"LGPL-3",
    'author': "Cybrosys Techno Solutions",
    'website': 'https://www.cybrosys.com',
    'category': 'Education',
    'summary': 'School Management',
    'description': """manage student,subject,department""",
    'sequence': 10,
    'application': True,
    'installable': True,
    'auto_install': True,
    'depends': ['base','mail', 'sale', 'contacts',],
    'data':[
        "security/school_management_groups.xml",
        "security/ir.model.access.csv",
        "security/school_student_record_rule.xml",
        "views/school_students_view.xml",
        "views/school_department_views.xml",
        "views/school_class_views.xml",
        "views/school_subject_views.xml",
        "data/sequence_data.xml",
        "data/school_class_data.xml",
        "data/school_department_data.xml",
        "data/school_subject_data.xml",
        "data/ ir_cron_data.xml",
        "data/mail_template_data.xml",
        "data/action_user_creation_data.xml",
        "views/school_year_views.xml",
        "views/school_clubs_views.xml",
        "views/sale_order_views.xml",
        "views/res_partner_views.xml",
        "views/school_leaves_views.xml",
        "views/school_exam_views.xml",
        "views/school_registerd_student_view.xml",
        "views/school_events_views.xml",
        "views/student_menu_views.xml",

],
}

